import Link from "next/link";

import { Layout } from "@/shared/components/Layout";
import { AnimatedTitle } from "@/shared/components/AnimatedTitle";
import { FramerImage } from "@/shared/components/FramerImage";

import { GitHubIcon } from "../(components)/NavBar/IconLink/Icons";
import project1 from "../../../public/images/projects/scavan.png";
import project2 from "../../../public/images/projects/scavan-partner-landing.png";
import project3 from "../../../public/images/projects/my-ecommerce.png";
import project4 from "../../../public/images/projects/retro-games.png";

export const metadata = {
  title: "AlexisGlez | Projects",
  description: "Generated by create next app",
};

const FeaturedProject: React.FunctionComponent<{
  type: string;
  title: string;
  summary: string;
  img: any;
  link: string;
  gitHubLink: string;
}> = ({ type, title, summary, img, link, gitHubLink }) => {
  return (
    <article className="w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 relative rounded-br-2xl dark:bg-dark dark:border-light lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl dark:bg-light xs:-right-2 sm:h-[102%] xs:w-[100%] xs:rounded-[1.5rem]" />
      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-lg lg:w-full"
      >
        <FramerImage
          src={img}
          alt={title}
          className="w-full h-auto"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.2 }}
          priority
          sizes="(max-width: 768px) 100vw, 50vw"
        />
      </Link>
      <div className="w-1/2 flex flex-col items-start justify-between pl-6 lg:w-full lg:pl-0 lg:pt-6">
        <span className="text-primary dark:text-primaryDark font-medium text-xl xs:text-base">
          {type}
        </span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold sm:text-sm">
            {title}
          </h2>
        </Link>
        <p className="my-2 font-medium text-dark dark:text-light sm:text-sm">
          {summary}
        </p>
        <div className="mt-2 flex items-center">
          <Link href={gitHubLink} target="_blank" className="w-10">
            <GitHubIcon />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold dark:bg-light dark:text-dark sm:px-4 sm:text-base"
          >
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};

const Project: React.FunctionComponent<{
  type: string;
  title: string;
  img: any;
  link: string;
  gitHubLink: string;
}> = ({ type, title, img, link, gitHubLink }) => {
  return (
    <article className="w-full flex flex-col items-center justify-between rounded-2xl border border-solid border-dark bg-light p-6 relative dark:bg-dark dark:border-light xs:p-4">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl dark:bg-light md:-right-2 xs:h-[102%] xs:rounded-[1.5rem]" />
      <Link
        href={link}
        target="_blank"
        className="w-full cursor-pointer overflow-hidden rounded-lg"
      >
        <FramerImage
          src={img}
          alt={title}
          className="w-full h-auto"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.2 }}
          priority
          sizes="(max-width: 768px) 100vw, 50vw"
        />
      </Link>
      <div className="w-full flex flex-col items-start justify-between mt-4">
        <span className="text-primary dark:text-primaryDark font-medium text-xl lg:text-lg md:text-base">
          {type}
        </span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2"
        >
          <h2 className="my-2 w-full text-left text-3xl font-bold lg:text-2xl">
            {title}
          </h2>
        </Link>
        <div className="w-full mt-2 flex items-center justify-between">
          <Link
            href={link}
            target="_blank"
            className="text-lg font-semibold underline md:text-base"
          >
            Visit
          </Link>
          <Link href={gitHubLink} target="_blank" className="w-8 md:w-6">
            <GitHubIcon />
          </Link>
        </div>
      </div>
    </article>
  );
};

export default function Projects() {
  return (
    <main className="flex items-center justify-center flex-col w-full mb-16 dark:text-light">
      <Layout className="pt-16">
        <AnimatedTitle
          text="See all my projects in my main website!"
          className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8"
        />
        <div className="grid grid-cols-12 gap-24 gap-y-32 mt-16 sm:mt-4 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0 sm:gap-y-16">
          <div className="col-span-12">
            <FeaturedProject
              type="Featured Project"
              title="Scavan"
              summary="Real state intelligence app to handle your listings!"
              img={project1}
              link="https://scavan.netlify.app"
              gitHubLink="https://github.com/AlexisGlez/scavan"
            />
          </div>
          <div className="col-span-6 sm:col-span-12">
            <Project
              type="Project"
              title="Scavan Parter Landing"
              img={project2}
              link="https://scavan-partner-landing.netlify.app"
              gitHubLink="https://github.com/AlexisGlez/scavan-partner-landing"
            />
          </div>
          <div className="col-span-6 sm:col-span-12">
            <Project
              type="Project"
              title="Retro Games"
              img={project4}
              link="https://retro-games.netlify.app"
              gitHubLink="https://github.com/AlexisGlez/retro-games"
            />
          </div>
          <div className="col-span-12">
            <FeaturedProject
              type="Featured Project"
              title="My Ecommerce"
              summary="A fullstack e-commerce implementation."
              img={project3}
              link="https://alexisglez-ecommerce.netlify.app"
              gitHubLink="https://github.com/AlexisGlez/my-ecommerce"
            />
          </div>
        </div>
      </Layout>
    </main>
  );
}
