import Link from "next/link";

import { Layout } from "@/shared/components/Layout";
import { AnimatedTitle } from "@/shared/components/AnimatedTitle";
import { FramerImage } from "@/shared/components/FramerImage";

import article1 from "../../../public/images/articles/doesyourcodereflectthestate.png";

import { ArticleItem } from "./(components)/ArticleItem";

export const metadata = {
  title: "AlexisGlez | Articles",
  description: "Generated by create next app",
};

const FeaturedArticle: React.FunctionComponent<{
  title: string;
  time: string;
  summary: string;
  link: string;
  img: any;
}> = ({ title, time, summary, link, img }) => {
  return (
    <li className="col-span-1 w-full p-4 bg-light border border-solid border-dark rounded-2xl relative dark:bg-dark dark:border-light">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl dark:bg-light" />
      <Link
        href={link}
        target="_blank"
        className="w-full inline-block cursor-pointer overflow-hidden rounded-lg"
      >
        <FramerImage
          src={img}
          alt={title}
          className="w-full h-auto"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.2 }}
          priority
          width={916}
          height={456}
          sizes="(max-width: 768px) 100vw, 50vw"
        />
      </Link>
      <Link href={link} target="_blank">
        <h2 className="capitalize text-2xl font-bold my-2 mt-4 hover:underline xs:text-lg">
          {title}
        </h2>
      </Link>
      <p className="text-sm mb-2">{summary}</p>
      <span className="text-primary font-semibold dark:text-primaryDark">
        {time}
      </span>
    </li>
  );
};

export default function Articles() {
  return (
    <main className="flex items-center justify-center flex-col w-full mb-16 overflow-hidden dark:text-light">
      <Layout className="pt-16">
        <AnimatedTitle
          text="See all my articles in my main website!"
          className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8"
        />
        <ul className="grid grid-cols-2 gap-16 lg:gap-8 md:grid-cols-1 md:gap-y-16">
          <FeaturedArticle
            title="Does your code actually reflect the state of your system? Flags vs Enums vs State Machines"
            time="9 min read"
            summary="Using flags to control the state of your system can become messy really quickly. Try using a state machine (or at least an enum) to overcome this 🔥"
            link="https://alexisglez.netlify.app/blogs/does-your-code-reflect-the-state-of-your-system"
            img={article1}
          />
          <FeaturedArticle
            title="Domain Driven Design"
            time="10 min read"
            summary="Domain Driven Design gives a set of guidelines and techniques that we can use to try to break larger domains into smaller domains."
            link="https://alexisglez.netlify.app/blogs/domain-driven-design"
            img="https://images.unsplash.com/photo-1533408874882-397bf377a8c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"
          />
        </ul>
        <h2 className="font-bold text-4xl w-full text-center my-16 mt-32 xs:text-lg">
          All Articles
        </h2>
        <ArticleItem
          title="Notes about Quantum Computing?"
          date="Sun 10th, Nov 2019"
          link="https://alexisglez.netlify.app/blogs/notes-about-quantum-computing"
          img="https://images.unsplash.com/photo-1550745165-9bc0b252726f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"
        />
        <ArticleItem
          title="What is the JamStack"
          date="Sat 14th, Sep 2019"
          link="https://alexisglez.netlify.app/blogs/what-is-the-jamstack"
          img="https://images.unsplash.com/photo-1506718468845-7578aa47670b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80"
        />
      </Layout>
    </main>
  );
}
